services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - comparison-tool-network
    volumes:
      - redis-data:/data
  backend:
    build:
      context: ./Flask-API
      dockerfile: Dockerfile.local
    ports:
     - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - HOST_TEMP_PATH=./backend_temp
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - comparison-tool-network
    volumes:
      - ./Flask-API:/app
      - /app/.venv
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend_temp:/app/backend_temp
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000/
    networks:
      - comparison-tool-network
    volumes:
      - ./client:/app
      - /app/node_modules
  executor-builder:
    build:
      context: ./Flask-API
      dockerfile: Dockerfile.executor
    image: sandboxed-plugin-executor:latest
networks:
  comparison-tool-network:
   driver: bridge
   
volumes:
  redis-data: