name: AWS CD (Pulumi Deploy)

on:
  push:
    branches:
      - dev
    paths:
      - 'infra/**'
      - 'Flask-API/**'

env:
  AWS_REGION: eu-north-1
  PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PULUMI_BACKEND_URL: s3://pulumi-state-bucket-5ae360c
  PULUMI_SKIP_UPDATE_CHECK: "true"

jobs:
  deploy:
    name: Infrastructure Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: infra/.venv
          key: venv-infra-${{ runner.os }}-${{ hashFiles('infra/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        working-directory: ./infra
        run: poetry install --no-interaction --no-root

      - name: Pulumi Login (S3)
        run: poetry run pulumi login ${{ env.PULUMI_BACKEND_URL }}
        working-directory: ./infra

      - name: Pulumi Up
        working-directory: ./infra
        run: poetry run pulumi up --stack dev --yes --skip-preview