name: Frontend CI

on:
  push:
    paths:
      - "client/**"
  pull_request:
    paths:
      - "client/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 8fa5a40 (CT- 74 - Implement caching for node modules in CI)
          
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
<<<<<<< HEAD
=======
>>>>>>> af53f7e (CT-74 - Add CI for frontend)
=======
>>>>>>> 8fa5a40 (CT- 74 - Implement caching for node modules in CI)

      - name: Install dependencies
        run: npm ci

      - name: Build project
<<<<<<< HEAD
<<<<<<< HEAD
        run: CI=false npm run build

      - name: Run tests
        run: npm test -- --watchAll=false --passWithNoTests
=======
        run: npm run build
=======
        run: CI=false npm run build
>>>>>>> 8fa5a40 (CT- 74 - Implement caching for node modules in CI)

      - name: Run tests
        run: npm test -- --watchAll=false
>>>>>>> af53f7e (CT-74 - Add CI for frontend)
